DROP TABLE IF EXISTS searches;

CREATE TABLE searches (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  externalUserIP INTEGER NOT NULL,
  query TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);