DROP TABLE IF EXISTS searches;

CREATE TABLE searches (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  client_ip INTEGER NOT NULL,
  search TEXT NOT NULL,
  searched_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);